### ISSUE TITLE
触控板不可用

### ISSUE THREAD

**Issue by six00** [jinmu333/HP_Probook_440_G6_EFI#1]
你好 我在安装时触控板是不可用的 请问你是怎么解决的？ 我和你一样的电脑 系统文件也差不多

**Comment by dreamhunter2333** [comment]
安装时如果想可用只能使用voodoops2 
其实进系统voodooi2c驱动的触摸板就可以用了

**Comment by six00** [comment]
我最近经常有触摸板失灵的情况 请问你有出现吗 而且我在idea开多了的情况下感觉cpu变频不正常 会卡顿 查看管理器也只用到了最多30%

**Comment by dreamhunter2333** [comment]
> 我最近经常有触摸板失灵的情况 请问你有出现吗 而且我在idea开多了的情况下感觉cpu变频不正常 会卡顿 查看管理器也只用到了最多30%

变频使用cpufriend我测试是没问题的可以百分之几百，至于触摸板失灵 你试试重建缓存

**Comment by six00** [comment]
> > 我最近经常有触摸板失灵的情况 请问你有出现吗 而且我在idea开多了的情况下感觉cpu变频不正常 会卡顿 查看管理器也只用到了最多30%
> 
> 变频使用cpufriend我测试是没问题的可以百分之几百，至于触摸板失灵 你试试重建缓存

好的 多谢 我在换了你更新之后的efi之后触摸暂时没有问题 但是亮度调节按钮失效了 我应该替换之前efi里面的哪个文件解决？
还有一个问题 我的cpu是i5 我看你使用的是i7 当前的cpufriend会根据cpu不同自动调节还是说需要我自己运行一遍脚本生成对应的文件呢？

**Comment by dreamhunter2333** [comment]
> > > 我最近经常有触摸板失灵的情况 请问你有出现吗 而且我在idea开多了的情况下感觉cpu变频不正常 会卡顿 查看管理器也只用到了最多30%
> > 
> > 
> > 变频使用cpufriend我测试是没问题的可以百分之几百，至于触摸板失灵 你试试重建缓存
> 
> 好的 多谢 我在换了你更新之后的efi之后触摸暂时没有问题 但是亮度调节按钮失效了 我应该替换之前efi里面的哪个文件解决？
> 还有一个问题 我的cpu是i5 我看你使用的是i7 当前的cpufriend会根据cpu不同自动调节还是说需要我自己运行一遍脚本生成对应的文件呢？

亮度调节按钮我不清楚你之前怎么驱动的，
至于cpu可以自己生成cpufriend的配置
